### ISSUE TITLE
dry-initializer not working with with_collection_parameter

### ISSUE THREAD

**Issue by niconisoria** [palkan/view_component-contrib#44]
## What did you do?

```
class Poncho::Component < ApplicationViewComponent
  with_collection_parameter :poncho

  option :poncho
end
```
## What did you expect to happen?

To define the :poncho option and work with the collection.

## What actually happened?

On a fresh install of the gem, dry-initializer is not working with the collection parameter.

## Additional context

```
Failure/Error: render_inline(component)
     
     ViewComponent::MissingCollectionArgumentError:
       The initializer for Poncho::Component doesn't accept the parameter `poncho`, which is required to render it as a collection.
     
       To fix this issue, update the initializer to accept `poncho`.
     
       See [the collections docs](https://viewcomponent.org/guide/collections.html) for more information on rendering collections.
```

## Environment

**Ruby Version:**

3.2

**Framework Version (Rails, whatever):**

Rails latest

**View Component Contrib Version:**

Latest

**Comment by palkan** [comment]
Thanks for the report!

View Component does [some Ruby introspection](https://github.com/ViewComponent/view_component/blob/5ae3c12e65628bf1d94d222737b0fd8ec0523b5d/lib/view_component/base.rb#L640) to check If you have explicitly specified the collection parameter in your `#initialize` method or use `**kwargs`. However, for some reason, it doesn't allow anonymous forwarding (`**` or `...`, used by [dry-initializer](https://github.com/dry-rb/dry-initializer/blob/8dc0d4b8443de89ef1dd892d774a5dd58d546785/lib/dry/initializer/mixin/root.rb#L10)): https://github.com/ViewComponent/view_component/blob/5ae3c12e65628bf1d94d222737b0fd8ec0523b5d/lib/view_component/base.rb#L695


My guess is that `**` is not allowed due to the args forwarding in Rails URL helpers usually included into components; thus, that would make the collection parameter check no-op in many situations. (At least, some older tests failed when I tried to remove this hack).

Since this problem is not specific to dry-initializer and would occur to any components setup relying on `...` or `**` in the `#initialize` method (e.g., for inheritance), I'd suggest discussing this problem at the View Component repo.
